name: "Continuous Integration - Pull Request"
on:
  pull_request_target:
    branches:
      - main
jobs:
  deployment-tests:
    runs-on: self-hosted
    strategy:
      matrix:
        profile: ["local-code"]
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Build + Deploy PR images to GKE
      timeout-minutes: 20
      run: |
        echo What is in the src directory
        cat src/helloserver/server.py

        NAMESPACE="pr${PR_NUMBER}"
        echo "::set-env name=NAMESPACE::$NAMESPACE"

        gcloud container clusters get-credentials $PR_CLUSTER --zone $ZONE --project $PROJECT_ID
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $NAMESPACE
        EOF

        echo Deploying application
        skaffold config set --global local-cluster false
        skaffold run --default-repo=gcr.io/$PROJECT_ID/refs/pull/$PR_NUMBER --tag=$PR_NUMBER --namespace=$NAMESPACE
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PR_CLUSTER: ${{ secrets.PR_CLUSTER_2 }}
        ZONE: ${{ secrets.PR_CLUSTER_2_ZONE }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
